# This workflow will build an Arch Linux ISO file when a release is created.
name: build parchiso per release
on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages via Pacman
        run: |
          pacman -Suy --noconfirm --noprogressbar
          pacman -Sy --noconfirm --noprogressbar --needed git archiso python python-pygithub reflector
      - name: Change pacman mirrors
        run: |
          reflector -n 3 --protocol https --save /etc/pacman.d/mirrorlist
          pacman -Syy
      
      - run: | 
          mkdir tmp
          mount -t tmpfs -o size=10G tmpfs  ./tmp
          
      - run: free -h  
        
      - name: Build image
        run: mkarchiso -v -w ./tmp ./iso
        
      - run: free -h
        
        
      # - name: Upload iso to the release
      #   env:
      #     API_KEY: ${{ secrets.GITHUB_TOKEN }}
      #     REPO_NAME: ${{ github.repository }}
      #     RELEASE_NAME: ${{ github.ref_name }}
        # run: python tools/upload_asset.py
